# core_actions - 自动生成的配置文件
# 系统核心动作插件，提供基础聊天交互功能，包括回复、不回复、表情包发送和聊天模式切换等核心功能。

# 插件启用配置
[plugin]

# 是否启用插件
enabled = true

# 配置文件版本
config_version = "0.1.0"


# 核心组件启用配置
[components]

# 是否启用'回复'动作
enable_reply = true

# 是否启用'不回复'动作
enable_no_reply = true

# 是否启用'表情'动作
enable_emoji = true

# 是否启用'切换到专注模式'动作
enable_change_to_focus = true

# 是否启用'退出专注模式'动作
enable_exit_focus = true


# 不回复动作配置（智能等待机制）
[no_reply]

# 最大等待超时时间（秒）
max_timeout = 1200

# LLM判断的最小间隔时间（秒），防止过于频繁
min_judge_interval = 1.0

# 累计消息数量达到此阈值时自动结束等待
auto_exit_message_count = 20

# Focus模式下，随机选择不回复的概率（0.0到1.0）
# 示例: 0.8
random_probability = 0.8

# 当发言过多时是否启用跳过LLM判断机制
skip_judge_when_tired = true

# 回复频率检查窗口时间（秒）
# 示例: 600
frequency_check_window = 600


# 表情动作配置
[emoji]

# Normal模式下，随机发送表情的概率（0.0到1.0）
# 示例: 0.15
random_probability = 0.1


[repeat]

# 是否启用复读功能
enable_repeat = true

# bot的复读几率
# 示例: 0.5
repeat_probability = 1


